export const references = [
 {id:'wcag',title:'W3C — WCAG 2.2',url:'https://www.w3.org/TR/WCAG22/',detail:'Critères 1.1.1 (alternatives textuelles), 1.3.1 (structure), 1.4.3 (contraste), 1.4.8 (présentation visuelle, niveau AAA). Les mesures web ne prouvent pas la conformité d’un document.'},
 {id:'sweller',title:'Sweller (1988) — Cognitive load during problem solving',url:'https://doi.org/10.1207/s15516709cog1202_4',detail:'La charge cognitive dépend de la tâche et des connaissances préalables. Des consignes segmentées peuvent réduire les demandes inutiles ; aucun seuil universel de mots n’en découle.'},
 {id:'mayer',title:'Mayer & Moreno (2003) — Nine ways to reduce cognitive load in multimedia learning',url:'https://doi.org/10.1207/S15326985EP3801_6',detail:'Principes de segmentation, signalisation et cohérence. Leur efficacité dépend du contexte et de la conception pédagogique.'},
 {id:'cast',title:'CAST — Universal Design for Learning Guidelines 3.0',url:'https://udlguidelines.cast.org/',detail:'Proposer plusieurs moyens de représentation et d’engagement, avec des choix tenant compte des besoins individuels.'},
 {id:'ef',title:'Diamond (2013) — Executive functions',url:'https://doi.org/10.1146/annurev-psych-113011-143750',detail:'Mémoire de travail, contrôle inhibiteur et flexibilité cognitive : cadre général, pas un diagnostic individuel.'}
];
export const profiles = {neurotypique:'Neurotypique',tdah:'TDAH',tsa:'TSA',combine:'TDAH + TSA',dyslexie:'Dyslexie',dysphasie:'Trouble développemental du langage',dyspraxie:'Trouble développemental de la coordination',visuel:'Déficience visuelle',auditif:'Déficience auditive',autre:'Autres besoins / profil personnalisé'};
export function analyze(document,target) {
 const text=document.text.trim(), sentences=text.split(/(?<=[.!?])\s+|\n+/).filter(Boolean), words=text.split(/\s+/).filter(Boolean);
 const young=target.age<=10, maxWords=young?18:25, needsSteps=target.needs.includes('attention')||['tdah','combine'].includes(target.profile);
 const literal=target.needs.includes('langage')||['tsa','combine','dysphasie'].includes(target.profile);
 const long=sentences.filter(s=>s.split(/\s+/).length>maxWords);
 const checks=[]; const add=(id,title,pass,observation,recommendation,refs,weight=1)=>checks.push({id,title,status:pass===null?'manual':pass?'pass':'issue',observation,recommendation,refs,weight});
 add('text','Texte exploitable',words.length>=20,`${words.length} mots extraits.`, 'Vérifier la fidélité du texte extrait, surtout après reconnaissance optique.', ['wcag']);
 add('sentences','Longueur des phrases',long.length===0,`${long.length} phrase(s) dépassent le repère de ${maxWords} mots ; repère pratique, pas une loi scientifique.`, 'Fractionner les longues phrases et garder les termes utiles au programme.', ['sweller','cast'],young?2:1);
 const blocks=text.split(/\n\s*\n/).filter(Boolean); const dense=blocks.filter(b=>b.split(/\s+/).length>100);
 add('density','Segmentation du contenu',dense.length===0,`${dense.length} bloc(s) dépassent 100 mots. Ce seuil est une heuristique.`, 'Séparer les idées en blocs, avec un objectif et des pauses de lecture.', ['mayer','sweller'],needsSteps?2:1);
 const multi=sentences.filter(s=>/\bet\b/i.test(s)&&/\b(lis|lisez|écris|écrivez|calcule|compare|explique|répond|souligne|entoure|observe)\w*/i.test(s));
 add('instructions','Consignes à plusieurs actions',multi.length===0,`${multi.length} consigne(s) potentiellement cumulatives. Détection lexicale à confirmer.`, 'Présenter une action par étape et une liste à cocher.', ['ef','sweller'],needsSteps?2:1);
 const figures=sentences.filter(s=>/\b(coup de main|jeter un œil|les doigts dans le nez|prendre la tête|évidemment|bien sûr)\b/i.test(s));
 add('literal','Clarté et langage explicite',figures.length===0,`${figures.length} expression(s) potentiellement implicite(s) repérée(s).`, 'Expliquer les expressions figurées et formuler explicitement les attentes.', ['cast'],literal?2:1);
 add('headings','Titres et structure',document.headings===undefined?null:document.headings>0,document.headings===undefined?'Structure non vérifiable dans ce format.':`${document.headings} titre(s) structurel(s) détecté(s).`, 'Employer des titres hiérarchisés et un ordre de lecture logique.', ['wcag','mayer']);
 add('font','Taille des caractères',document.minFont===undefined?null:document.minFont>=12,document.minFont===undefined?'Taille réelle des caractères non mesurée.':`Plus petite taille détectée : ${Math.round(document.minFont*10)/10} points, avant zoom. Le repère de 12 points est indicatif.`, 'Permettre l’agrandissement et vérifier une taille lisible avec l’élève.', ['wcag','cast'],target.profile==='visuel'?2:1);
 add('contrast','Contraste, couleurs et images',null,'Contraste et signification des images à vérifier manuellement.','Vérifier un contraste suffisant, les alternatives aux images et l’absence de consignes fondées uniquement sur la couleur.', ['wcag']);
 add('curriculum','Pertinence pédagogique et prérequis',null,`Public : ${profiles[target.profile]}, ${target.age} ans, niveau ${target.level}. La correspondance au programme n’est pas déduite du texte.`, 'Vérifier l’objectif, les prérequis et l’exactitude avec l’enseignant ; expliciter le vocabulaire nouveau.', ['cast','sweller']);
 const measured=checks.filter(c=>c.status!=='manual'), total=measured.reduce((a,c)=>a+c.weight,0), score=total?Math.round(100*measured.filter(c=>c.status==='pass').reduce((a,c)=>a+c.weight,0)/total):null;
 return {target,score,checks,references,metrics:{words:words.length,sentences:sentences.length,measured:measured.length,total:checks.length},warnings:document.warnings||[],text,summary:checks.filter(c=>c.status==='issue').map(c=>c.title),method:'Indice heuristique pondéré : critères satisfaits / critères mesurés. Les contrôles manuels sont exclus. Ce score ne mesure ni les connaissances accessibles, ni la compréhension, ni une conformité WCAG. Un profil ne prédit pas les besoins d’un élève ; confirmer les aménagements avec lui et l’équipe pédagogique.'};
}
export const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function adaptedHtml(result,name){
 const attentive=result.target.needs.includes('attention')||['tdah','combine'].includes(result.target.profile);
 const size=result.target.profile==='visuel'?24:result.target.age<=10||result.target.profile==='dyslexie'?22:20;
 const advice={neurotypique:'Expliciter les objectifs et proposer plusieurs façons de répondre.',tdah:'Afficher une étape à la fois, prévoir une pause et un repère de progression.',tsa:'Rendre les attentes prévisibles et expliquer le vocabulaire implicite.',combine:'Prévoir des étapes courtes, des consignes explicites et un déroulé prévisible.',dyslexie:'Permettre la lecture vocale et ajuster la taille du texte avec l’élève.',dysphasie:'Expliquer le vocabulaire et vérifier la compréhension des consignes.',dyspraxie:'Proposer une réponse orale ou numérique selon les besoins.',visuel:'Ajuster le grossissement et fournir des alternatives aux images.',auditif:'Fournir par écrit les informations et consignes orales.',autre:'Définir les aménagements avec l’élève et l’équipe pédagogique.'}[result.target.profile];
 const blocks=result.text.split(/\n+/).filter(Boolean).flatMap(p=>p.split(/(?<=[.!?])\s+/));
 return `<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Support adapté</title><style>body{font:${size}px/1.8 Arial,sans-serif;max-width:70ch;margin:40px auto;padding:24px;color:#172535;background:#fff}h1,h2{line-height:1.3}li{margin:1em 0}button{font:inherit;padding:12px}@media print{button{display:none}}</style><h1>${escapeHtml(name)}</h1><p>Version de lecture segmentée — ${escapeHtml(result.target.level)}, ${result.target.age} ans.</p><p>Le texte extrait est conservé, sans simplification automatique du sens. Images, tableaux et mise en page originale ne sont pas reproduits. Vérifiez les erreurs d’extraction avant utilisation.</p><button onclick="window.print()">Imprimer / enregistrer en PDF</button><h2>Repères pour ce public</h2><p>${escapeHtml(advice)} Ces pistes sont à confirmer individuellement.</p><h2>Mon parcours</h2><p>Je lis un bloc à la fois. Je note les mots à expliquer. Je peux demander une pause ou une autre présentation.</p><h2>Support</h2>${blocks.map((p,i)=>`<section><h3>${attentive?'Étape':'Bloc'} ${i+1}</h3>${attentive?'<label><input type="checkbox"> Lecture terminée</label>':''}<p>${escapeHtml(p)}</p></section>`).join('')}<h2>À vérifier avec l’enseignant</h2><ul>${result.checks.filter(c=>c.status!=='pass').map(c=>`<li>${escapeHtml(c.recommendation)}</li>`).join('')}</ul></html>`;
}
